### ISSUE TITLE
Anton code it 8: Phone numbers из CodeWars

### ISSUE THREAD

**Issue by evilj0e** [evilj0e/antoncodeit#3]
Description: http://bit.ly/antoncodeit-description-8
Estimation: 8 October

Send your own solution as PR to the issue.
One of your solutions can get code review after my solution & explanation.

**Comment by evilj0e** [comment]
https://www.youtube.com/watch?v=LOtN0TYOGW8

**Comment by Razdva122** [comment]
https://pastebin.com/qZNm3cKH - Решение почти полностью идентичное.

и пару интересных задач на мой вкус может понравятся :
Codewars :
https://www.codewars.com/kata/55eaf138c1f4e9eef1000047
Leetcode : 
https://leetcode.com/problems/minimum-index-sum-of-two-lists/
https://leetcode.com/problems/letter-combinations-of-a-phone-number/

**Comment by evilj0e** [comment]
The winner is @He4et. Your code will be reviewed as soon as possible.
